### PR TITLE
fix(templates): orgId query param on manual alerts

### PR DESCRIPTION
**Pull request by aos**
This PR fixes the issue found here: https://github.com/grafana/grafana/issues/66427. I've also added tests for this.

NB: When I was attempting to test this, the Grafana docker image was failing to build. However, this PR: https://github.com/grafana/grafana/pull/66622 fixed my issues, and I used the corresponding branch to test my fix.

### Testing alert with `orgId` parameter
grafana_alert_orgid

Related to https://github.com/grafana/grafana/pull/57123 that introduced support for orgID parameter in URL

### CODE REVIEW

**Review by yuri-tceretian — APPROVED** [review]
LGTM

**Comment by yuri-tceretian** [comment]
Let's wait for @grobinson-grafana to review it too.

**Comment by aos** [comment]
Hey @yuri-tceretian @grobinson-grafana - just pinging y'all about this. Thank you!

**Comment by aos** [comment]
Hi - just pinging on this again. I'm happy to resolve the conflicts but please let me know if there's some other work that needs to happen before this can go in? It would be really handy to have. Esp. now that Grafana v9.5+  makes Organizations more apparent.

**Review by grobinson-grafana — APPROVED** [review]

**Pull request merged**
