### PR TITLE
Remove hardocded pagerduty APIURL

### LINKED ISSUE #82741: Allow user to choose between Pagerduty global and Pagerduty EU endpoint
### Discussed in https://github.com/grafana/grafana/discussions/67187

<div type='discussions-op-text'>

<sup>Originally posted by **guusbeckett** April 25, 2023</sup>
At our company we use the PagerDuty EU endpoint, but it is not yet possible to use the EU endpoint of PagerDuty. 
As PagerDuty and PagerDuty EU are separate platforms, we cannot simply connect to the global endpoint and expect it to work.

I currently have a custom build that just changes the PagerDuty url to the EU one;
`https://events.pagerduty.com/v2/enqueue` becomes `https://events.eu.pagerduty.com/v2/enqueue`

Is it an idea to provide users with a new alert manager recipient and add _PagerDuty EU_ or would you prefer something else?

I'd be happy to implement this in the code.</div>

### PR DESCRIPTION
**Pull request by gaurav1999**
- Fixes https://github.com/grafana/grafana/issues/82741

### CODE REVIEW

**Comment by gaurav1999** [comment]
@armandgrillet Have fixed this to use configurable APIURL and updated the tests as well. Would be happy to iterate over the reviewers feedback.

**Comment by gaurav1999** [comment]
Requesting for review @grobinson-grafana / @JohnnyQQQQ

**Comment by gaurav1999** [comment]
@gotjosh  Requesting review /

**Comment by grobinson-grafana** [comment]
Hi! I've requested a review from the Alerting squad. @gotjosh and I are no longer on that squad I'm afraid.

**Review by yuri-tceretian — APPROVED** [review]
LGTM.
This needs a change in Grafana https://github.com/grafana/grafana/blob/14f018e3fc3dd7a7ffba68cd7ee1db59f8939647/pkg/services/ngalert/notifier/channels_config/available_channels.go#L365

**Comment by yuri-tceretian** [comment]
Please fix lint errors and I will merge
```
receivers/pagerduty/config.go:18:2: var-naming: const DefaultApiUrl should be DefaultAPIURL (revive)

	DefaultApiUrl   = "https://events.pagerduty.com/v2/enqueue"

	^

receivers/pagerduty/config.go:56:2: var-naming: struct field ApiURL should be APIURL (revive)

	ApiURL    string            `json:"api_url,omitempty" yaml:"api_url,omitempty"`

	^

```

**Comment by gaurav1999** [comment]
@yuri-tceretian , any cli tool that you recommend i can check to run and see lint issues ?, I am coming from node background any hints would be super useful, thanks!

**Comment by yuri-tceretian** [comment]
In go-world, we use `golangci-lint` (https://golangci-lint.run/)
In the repository root, you can run `make lint` and it will install all CLI tools needed for the command and verify the code.

**Comment by gaurav1999** [comment]
Thanks a ton @yuri-tceretian , done from my end, lemme know if anything else is needed to get this shipped  🚢 🚀

**Comment by gaurav1999** [comment]
> LGTM. This needs a change in Grafana https://github.com/grafana/grafana/blob/14f018e3fc3dd7a7ffba68cd7ee1db59f8939647/pkg/services/ngalert/notifier/channels_config/available_channels.go#L365

Alright will open PR in parallel, this could be independent right ?

**Comment by yuri-tceretian** [comment]
> Alright will open PR in parallel, this could be independent right ?

There is a convention within the team to open PRs in two repo and review them together and merge relatively the same time. This is needed to avoid drift when changes in this repository pile up and block each other.

**Comment by yuri-tceretian** [comment]
Can you please change the name of the property to just `url`.
In vanilla Alertmanager there is [already a field ](https://github.com/grafana/prometheus-alertmanager/blob/3d49ff83c74e253fc60b7659d952b24c59c44962/config/notifiers.go#L301) that is used for the same purpose.  We try to keep those config as similar as possible.

Sorry, I forgot about that when I reviewed it earlier

**Comment by gaurav1999** [comment]
> Can you please change the name of the property to just `url`. In vanilla Alertmanager there is [already a field ](https://github.com/grafana/prometheus-alertmanager/blob/3d49ff83c74e253fc60b7659d952b24c59c44962/config/notifiers.go#L301) that is used for the same purpose. We try to keep those config as similar as possible.
> 
> Sorry, I forgot about that when I reviewed it earlier

N.P, done!

**Review by yuri-tceretian — APPROVED** [review]

**Comment by yuri-tceretian** [comment]
Great job! Thank you so much!

**Pull request merged**
